### ISSUE TITLE
ng-class conversion

### ISSUE THREAD

**Issue by JeremyLikness** [ngmigrate/ngmigrate.github.io#14]
Article to show differences between using the ng-class directive and binding directly to [class]

**Comment by juristr** [comment]
@toddmotto I could contribute such an article, as I've already written a [similar one on my blog](http://juristr.com/blog/2016/01/learning-ng2-dynamic-styles/).

Possible titles:

- "From ng-class to ngClass"
- "Applying style: in Angular 1 and Angular 2"
- ... _(not very creative right now)_

//cc @JeremyLikness
