### ISSUE TITLE
Using third party angular 1.x libs from angular 2

### ISSUE THREAD

**Issue by dezoxel** [ngmigrate/ngmigrate.github.io#24]
Greetings,

I have an existing project on Angular 1.x using Angular Material 1.x. I've faced with an issue that I can't use Angular Material 2 since it is in alpha stage and some really important components are missing so I decided to use Angular Material 1.x with Angular 2. But thats a problem too because I can't use, for instance, md-autocomplete component:

```
Error: Template parse errors:
'md-autocomplete' is not a known element: 
...
```

So here is question: how to use third party components written in Angular 1.x inside Angular 2?

**Comment by toddmotto** [comment]
Hi, this isn't a support channel - I'd suggest asking this question on Stackoverflow.
