### ISSUE TITLE
Add contribution links

### ISSUE THREAD

**Issue by toddmotto** [ngmigrate/ngmigrate.github.io#3]
Would love some help from others in the industry if they would like to submit an article or even an idea, will work on making contributing more visible.

**Comment by rajzshkr** [comment]
I'm interested in contributing to this project. Let me know how can I help you??

**Comment by toddmotto** [comment]
@rajzshkr Ah awesome! Let me scope out the contributing file so I know what's happening and lay it out for those who wish to contribute :) ! Thanks!

**Comment by rajzshkr** [comment]
@toddmotto Thanks, looking for contribution file.
