### ISSUE TITLE
Link to ngMigrate does not navigate to correct site

### ISSUE THREAD

**Issue by rze89** [ngmigrate/ngmigrate.github.io#4]
When navigating to the ngMigrate repository [here](https://github.com/ngmigrate), the link under the 'ngMigrate by Kendo UI' header does not navigate to the current site where ngMigrate is being hosted [here](http://ngmigrate.telerik.com). While this is not a major issue, I figured it may have just slipped by. Really enjoying the site by the way. :+1:

**Comment by toddmotto** [comment]
Thanks, all fixed :)
